### ISSUE TITLE
Why coupling the client with specific PSR18 implementation?

### ISSUE THREAD

**Issue by vsouz4** [DoclerLabs/api-client-generator#18]
It's quite common that an API will communicate with other APIs (plural), so you might end up requiring couple or many api clients on your `composer.json`. If these clients all depend on some specific external package version, we have lots of conflict situations when we try to upgrade stuff.

I've checked the source code of this project, and the generated clients are, if I'm not mistaken, pretty much ready to work based on PSR interfaces (more specifically, I'm talking about PSR-18), except for the `MyApiClientFactory` class.

My idea is that `MyApiClientFactory::create` signature would be, instead of:
```php
    public function create(string $baseUri, array $options = []): MyApiClient
```
something like:
```php
    public function create(ClientInterface $client): MyApiClient
```
`ClientInterface` being `Psr\Http\Client\ClientInterface` (PSR-18).

So, pretty much, we give the responsibility of client creation to who's using the api client, applying Dependency Inversion. It'll be a factory still, for we need to create the service provider etc. but then at least we work agnostically, with the PSR-18 implementation chosen externally (we can even "suggests" on composer all the options one can use). 

Does it make sense? Can I create a PR about this, maybe major update 4.x considering it'll break how we create/configure the api client?

**Comment by mikemadisonweb** [comment]
Hi @vsouz4! Generally, it is a good thing and a logical continuation of the PSR decoupling course. The only source of issues possible after that which I worry about is the unpredictability of the client's behavior not created within the package. As the library has no control over the base client creation you have no way of preventing an issue from happening other than recommendations in the documentation.
For example, we require Guzzle http_errors param to be false, otherwise, our own error handling would not work.
Other than that, I am positive about this change. Probably benefits outweigh the drawbacks in this case.
