### ISSUE TITLE
Improve HEAD query support

### ISSUE THREAD

**Issue by JasonBenett** [DoclerLabs/api-client-generator#4]
Hello all,

I am currently generating an API client from an open-api file where there is a HEAD endpoint. This endpoint allows me to expose some aggregate data in the Response Header such as "X-Count", "X-Sum" and so on. 
But, please rectify if I am wrong, from the generated client it's currently impossible to access those header values since there is no ResponseMapper and Schema created for this HTTP Verb?

Is it panned to implement this feature? Or maybe I can try to add it through a PR?

Regards,
Jason

**Comment by mikemadisonweb** [comment]
Hi, actually it makes sense to do that. The issue is currently in the client we always map the raw data to objects on the fly. So you don't have direct access to the HTTP related information, like status code or headers. We would add it.
Please provide an example of the specification you have and we would include this as a task for the next version.

**Comment by JasonBenett** [comment]
Thank you for the quick reply. Hereafter an example of a specification with a head call: 

```yaml
  /my/endpoint:
    head:
      operationId: customId
      responses:
        '200':
          headers:
            X-Count:
              schema:
                type: integer
            X-Sum:
              schema:
                type: number
            X-Cool-Stuff:
              schema:
                type: number
                format: float
```

**Comment by mikemadisonweb** [comment]
Added in #5.
